### PR TITLE
feat(@angular-ru/common): rows copy feature and reworks

### PR DESCRIPTION
**Pull request by Schirbak**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
-   [x] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by splincode** [comment]
why excel service move to table-utils?

**Review by splincode — CHANGES_REQUESTED** [review]
I respect your work, it is really good PR. However, the concept of excel was that it should be a separate subpackage (`@angular-ru/common/excel` and `@angular-ru/cdk/excel` later) and does not apply to tables.

**Comment by Schirbak** [comment]
I merged them into one pack because they are very similar in logic and are almost equally tested. then this is the way: return excel and make another table-clipboard pack.

**Comment by splincode** [comment]
`return excel and make another table-clipboard pack` good idea

**Comment by splincode** [comment]
Need rework

**Pull request closed without merging**
