### PR TITLE
feat: add transform-date-to-format

### PR DESCRIPTION
**Pull request by StepaZol**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
-   [x] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by Schirbak — APPROVED** [review]
horosho

**Review by splincode — APPROVED** [review]
LGTM

**Comment by Schirbak** [comment]
@splincode, can you please add @StepaZol to the project? he can't start the pipeline from his own repository, so we can't pass all the checks for this PR.

**Comment by splincode** [comment]
@Schirbak done

**Pull request closed without merging**
