### PR TITLE
feat(@angular-ru/common): add isFilledList method

### PR DESCRIPTION
**Pull request by Schirbak**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows our guidelines: https://github.com/ngxs/store/blob/master/CONTRIBUTING.md#commit
-   [x] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by mansurishmuhametov — APPROVED** [review]

**Review by mansurishmuhametov — APPROVED** [review]

**Comment by Schirbak** [comment]
```ts

function isFilledList<T>(array: T[]): array is [T, ...T[]] {
    // return ...
}

function isMultipleList<T>(array: T[]): array is [T, T, ...T[]] {
    // return ...
}

function isSingleList<T>(array: T[]): array is [T] {
    // return ...
}

function isEmptyList<T>(array: T[]): array is [] {
    // return ...
}
```
тайпгарды так и напрашиваются 🤤

**Comment by splincode** [comment]
запилишь тайпгарды?

**Comment by Schirbak** [comment]
> запилишь тайпгарды?

не развалится ничего?)

**Comment by splincode** [comment]
проверить надо, в node_modules подложи артефакты и сбилди проект

**Pull request merged**
